#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files > "$dir/tag_files"
[ -d ./bots ] && git -C bots ls-files | sed 's/^/bots\//' >> "$dir/tag_files"
ctags --tag-relative -L "$dir/tag_files" -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
